main: net.ddns.haruhionly.haruhi.Haruhi

name: Haruhi

version: 0.4.0

description: Minecraft to Discord chat bindings

api-version: 1.21.1

author: Noah

commands:
  haruhi:
    description: Directly interact with the Brigade Leader Haruhi Discord bot
    usage: "Usage: /<command> [channel|reply|r|user] [options] <message>"

